### ISSUE TITLE
Base Case && Pseudocode

### ISSUE THREAD

**Issue by igalakhov** [fareeha09/FMRadioMazeSolver#3]
# Base Case
Seems fine to me. But I think Mr. Holmes had some kind of problem with ours and yours looks similar. Check our repo maybe?
# Pseudocode
I think you should try and keep the pseudocode consistent. If you write one of the if statements with "(", why not write the other one with it too?
Also, write a proper return statements for:
```
if true, take another step

if false, go back a step
```

**Comment by Mandy15** [comment]
Thank you! Attempted to clear up these issues in the writing.
